name: Scheduled Lighthouse Test
on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          uploadArtifacts: true
          temporaryPublicStorage: false
          configPath: ./lighthouse-configs/smartphone/lighthouserc.yml
          urls: |
            https://handheld.tokyo/
